Add gatling benchmarks
kuzzleio/kuzzle-benchmark pull request #2
Opened 2018-11-28 13:03 UTC by Aschen

## What does this PR do ?

Add a Gatling benchmarking suite.

### How should this be manually tested?

  - Step 1 :
  - Step 2 :
  - Step 3 :  
  ...

### Other changes

### Boyscout

2018-12-03 08:43 UTC, scottinet commented on gatling/commands.rb
> +class Babysitter
![I see what you did there](https://i3.kym-cdn.com/photos/images/original/000/074/461/I-SEE-WHAT-YOU-DID-THERE_HOLYSHIT.jpg)

2018-12-03 08:46 UTC, scottinet commented
Just a thought: why using Ruby for command parsing, where the project is written in Node.js, which can already easily parse commands using, for instance, [yargs](https://www.npmjs.com/package/yargs)?

I'm not exactly fond of adding layers over layers of languages when there is no added value to it.

2018-12-03 09:03 UTC, scottinet requested changes
It's not clear to me if the `results/*` files are benchmarks examples or mistakenly added to the project: 
in one hand I can see how these files can be useful but, in the other hand, I find no reference to those in the PR description nor in the README file.

In either cases, the gatling result directory should be put in the `.gitignore` file. And if the .html files in this PR really are examples, then those should be put in another, more explicitly named directory.

2019-01-30 13:25 UTC, closed without merging

2019-01-30 13:25 UTC, Aschen commented
@Yoann-Abbes PR is much more complete